import { create } from "zustand";
import axios from "axios";

// Define the shape of an event object (adjust according to your API response)
interface Event {
  id: string; // Assuming `id` is a string; adjust as needed
  title: string;
  description?: string; // Optional field
  date: string;
  // Add other event properties as needed
}

// Define the shape of the store's state and actions
interface StoreState {
  events: Event[];
  fetchEvents: () => Promise<void>;
  addEvent: (event: Omit<Event, "id">) => Promise<void>; // `id` is omitted because it's generated by the server
  updateEvent: (id: string, event: Partial<Event>) => Promise<void>; // `Partial` allows updating only some fields
  deleteEvent: (id: string) => Promise<void>;
}

const useStore = create<StoreState>((set) => ({
  events: [],
  fetchEvents: async () => {
    try {
      const response = await axios.get<Event[]>("/api/events"); // Specify the response type as `Event[]`
      set({ events: response.data });
    } catch (error) {
      console.error("Error fetching events:", error);
    }
  },
  addEvent: async (event) => {
    try {
      const response = await axios.post<Event>("/api/events", event); // Specify the response type as `Event`
      set((state) => ({ events: [...state.events, response.data] }));
      await useStore.getState().fetchEvents(); // Refresh the events list
    } catch (error) {
      console.error("Error adding event:", error);
    }
  },
  updateEvent: async (id, event) => {
    try {
      await axios.put("/api/events", { id, ...event });
      await useStore.getState().fetchEvents(); // Refresh the events list
    } catch (error) {
      console.error("Error updating event:", error);
    }
  },
  deleteEvent: async (id) => {
    try {
      await axios.delete("/api/events", { data: { id } });
      await useStore.getState().fetchEvents(); // Refresh the events list
    } catch (error) {
      console.error("Error deleting event:", error);
    }
  },
}));

export default useStore;